/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calculadora.presentacion;

import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author antho
 */
public class JFMenuCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JFMenuCalculadora
     */
    public JFMenuCalculadora() {
        initComponents();
        mostrarCalculadoraBasica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        pContenedor = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCalcBasica = new javax.swing.JButton();
        btnCalcCien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pContenedor.setBackground(new java.awt.Color(204, 255, 204));
        pContenedor.setMinimumSize(new java.awt.Dimension(500, 500));
        pContenedor.setPreferredSize(new java.awt.Dimension(500, 500));
        pContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JPanel1.add(pContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 510, 450));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        btnCalcBasica.setBackground(new java.awt.Color(153, 153, 255));
        btnCalcBasica.setText("Calculadora Basica");
        btnCalcBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcBasicaActionPerformed(evt);
            }
        });

        btnCalcCien.setBackground(new java.awt.Color(153, 153, 255));
        btnCalcCien.setText("Calculadora Cientifica");
        btnCalcCien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnCalcBasica, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcCien, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcCien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcBasica, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        JPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcCienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCienActionPerformed

        mostrarCalculadoraCientifica();
        
      
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcCienActionPerformed

    private void btnCalcBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcBasicaActionPerformed

       mostrarCalculadoraBasica();
        
        
        
    }//GEN-LAST:event_btnCalcBasicaActionPerformed

    public void mostrarCalculadoraBasica(){
         JPCalculadoraBasica panelCalcBasica= new JPCalculadoraBasica();
        panelCalcBasica.setSize(500,500);
        panelCalcBasica.setLocation(0,0);
        
        pContenedor.removeAll();
        pContenedor.add(panelCalcBasica, new AbsoluteConstraints(0,0,-1,-1));
        pContenedor.revalidate();
        pContenedor.repaint();
    
    }
    
     public void mostrarCalculadoraCientifica(){
         JPCalculadoraCientifica panelCalcCientifica= new JPCalculadoraCientifica();
        panelCalcCientifica.setSize(500,500);
        panelCalcCientifica.setLocation(0,0);
        
        pContenedor.removeAll();
        pContenedor.add(panelCalcCientifica, new AbsoluteConstraints(0,0,-1,-1));
        pContenedor.revalidate();
        pContenedor.repaint();
    
    }
     
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnCalcBasica;
    private javax.swing.JButton btnCalcCien;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pContenedor;
    // End of variables declaration//GEN-END:variables
}
