/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.calculadora.presentacion;

import com.calculadora.logicanegocio.CalculadoraBasica;

/**
 *
 * @author antho
 */
public class JPCalculadoraBasica extends javax.swing.JPanel {

    double num1;
    double num2;
    String signo;
    
    /**
     * Creates new form JPCalculadoraBasica
     */
    public JPCalculadoraBasica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeis = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        btnIgual = new javax.swing.JButton();
        btnNega = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSeis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeis.setText("6");
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        add(btnSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 80, 52));

        btnCinco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCinco.setText("5");
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        add(btnCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 52));

        btnPunto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 80, 52));

        btnDos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDos.setText("2");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, 52));

        btnUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUno.setText("1");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 52));

        btnCuatro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 52));

        btnCero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCero.setText("0");
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        add(btnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 80, 52));

        btnSumar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 57, 52));

        btnTres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTres.setText("3");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 80, 52));

        btnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 57, 52));

        btnOcho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOcho.setText("8");
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        add(btnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, 52));

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton13.setText("7");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 52));

        btnDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 57, 52));

        btnNueve.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNueve.setText("9");
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        add(btnNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, 52));

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 57, 52));

        btnCE.setBackground(new java.awt.Color(255, 153, 0));
        btnCE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 150, 90, 52));

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 34, 440, 80));

        btnIgual.setBackground(new java.awt.Color(51, 51, 255));
        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 80, 50));

        btnNega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNega.setText("Neg");
        btnNega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegaActionPerformed(evt);
            }
        });
        add(btnNega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed

        txtResultado.setText(txtResultado.getText()+"4");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed


        txtResultado.setText(txtResultado.getText()+"0");
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed

        txtResultado.setText(txtResultado.getText()+"1");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUnoActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

         txtResultado.setText(txtResultado.getText()+"7");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed

         txtResultado.setText(txtResultado.getText()+"2");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed

         txtResultado.setText(txtResultado.getText()+"5");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed

         txtResultado.setText(txtResultado.getText()+"8");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed

         txtResultado.setText(txtResultado.getText()+"9");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed

         txtResultado.setText(txtResultado.getText()+"6");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed

         txtResultado.setText(txtResultado.getText()+"3");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed

        if(!(txtResultado.getText().contains("."))){
         txtResultado.setText(txtResultado.getText()+".");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed

        
       if(!txtResultado.getText().equals("")){
             num1 = Double.parseDouble(txtResultado.getText());
             signo= "+";
            txtResultado.setText("");
          
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed

       if(!txtResultado.getText().equals("")){
             num1 = Double.parseDouble(txtResultado.getText());
             signo= "-";
            txtResultado.setText("");
          
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed


         if(!txtResultado.getText().equals("")){
             num1 = Double.parseDouble(txtResultado.getText());
             signo= "*";
            txtResultado.setText("");
          
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed

        if(!txtResultado.getText().equals("")){
             num1 = Double.parseDouble(txtResultado.getText());
            signo= "/";
            txtResultado.setText("");
          
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed

        CalculadoraBasica c= new CalculadoraBasica();

        
        num2= Double.parseDouble(txtResultado.getText());
      
      switch(signo){
          
          case "+":
              txtResultado.setText(quitarCero(c.sumar(num1, num2)));
              break;
          
          case "-":
              txtResultado.setText(quitarCero(c.restar(num1, num2)));
              break;
              
          case "*":
              txtResultado.setText(quitarCero(c.multiplicar(num1, num2)));
              break;
              
          case "/":
             txtResultado.setText(quitarCero(c.dividir(num1, num2)));
              break;


      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
      
      txtResultado.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnNegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegaActionPerformed

        txtResultado.setText(txtResultado.getText()+"-");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNegaActionPerformed

    

    public String quitarCero(Double resultado){
        String retorno="";
    
        retorno= Double.toString(resultado);
        
        if(resultado%1==0){
            retorno=retorno.substring(0,retorno.length()-2);
        }
    
        return retorno;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNega;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton jButton13;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
